service: kyllikki-example-minimal

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

functions:
  apihandler:
    handler: minimal/serverless_apihandler.main
    events:
      - http:
          cors: true
          path: pets
          method: get
  openapi:
    handler: minimal/serverless_openapihandler.main
    events:
      - http:
          cors: true
          path: openapi
          method: get
